import 'package:mobx/mobx.dart';
import 'package:mobile_ai_erp/domain/entity/cart/wishlist_item.dart';
import 'package:mobile_ai_erp/data/repository/cart/cart_repository.dart';
import 'package:uuid/uuid.dart';

part 'wishlist_store.g.dart';

/// MobX store for managing wishlist state and operations
class WishlistStore = WishlistStoreBase with _$WishlistStore;

/// Base class for WishlistStore (generated by build_runner)
abstract class WishlistStoreBase with Store {
  final CartRepository _cartRepository;

  // Current user ID
  final String userId;

  WishlistStoreBase({
    required CartRepository cartRepository,
    required this.userId,
  }) : _cartRepository = cartRepository;

  // ============ OBSERVABLES ============

  /// List of wishlist items
  @observable
  List<WishlistItem> items = [];

  /// Loading state
  @observable
  bool isLoading = false;

  /// Error message
  @observable
  String? errorMessage;

  /// Sort order: 'recent', 'price-low', 'price-high', 'name'
  @observable
  String sortBy = 'recent';

  /// Filter/search query
  @observable
  String searchQuery = '';

  /// Selected items for bulk operations
  @observable
  List<String> selectedProductIds = [];

  // ============ COMPUTED ============

  /// Total number of items in wishlist
  @computed
  int get itemCount => items.length;

  /// Total value of wishlist
  @computed
  double get totalWishlistValue =>
      items.fold(0, (sum, item) => sum + item.effectivePrice);

  /// Potential savings from wishlist items
  @computed
  double get potentialSavings =>
      items.fold(0, (sum, item) => sum + (item.savingsAmount ?? 0));

  /// Items on sale in wishlist
  @computed
  List<WishlistItem> get itemsOnSale =>
      items.where((item) => item.isOnSale).toList();

  /// Items with low stock
  @computed
  List<WishlistItem> get lowStockItems =>
      items.where((item) => item.isLowStock).toList();

  /// Items out of stock
  @computed
  List<WishlistItem> get outOfStockItems =>
      items.where((item) => item.isOutOfStock).toList();

  /// Filtered and sorted wishlist items
  @computed
  List<WishlistItem> get filteredAndSortedItems {
    var filtered = items;

    // Apply search filter
    if (searchQuery.isNotEmpty) {
      filtered = filtered
          .where((item) => item.productName
              .toLowerCase()
              .contains(searchQuery.toLowerCase()))
          .toList();
    }

    // Apply sorting
    var sorted = List<WishlistItem>.from(filtered);
    switch (sortBy) {
      case 'price-low':
        sorted.sort((a, b) => a.effectivePrice.compareTo(b.effectivePrice));
        break;
      case 'price-high':
        sorted.sort((a, b) => b.effectivePrice.compareTo(a.effectivePrice));
        break;
      case 'name':
        sorted.sort((a, b) => a.productName.compareTo(b.productName));
        break;
      case 'recent':
      default:
        sorted.sort((a, b) => b.dateAdded.compareTo(a.dateAdded));
    }

    return sorted;
  }

  /// Number of selected items
  @computed
  int get selectedItemsCount => selectedProductIds.length;

  /// Check if wishlist is empty
  @computed
  bool get isEmpty => items.isEmpty;

  // ============ ACTIONS ============

  /// Load wishlist from repository
  @action
  Future<void> loadWishlist() async {
    isLoading = true;
    errorMessage = null;

    try {
      items = await _cartRepository.getWishlist(userId);
    } catch (e) {
      errorMessage = e.toString();
    } finally {
      isLoading = false;
    }
  }

  /// Add item to wishlist
  @action
  Future<void> addToWishlist(WishlistItem item) async {
    isLoading = true;
    errorMessage = null;

    try {
      // Generate ID if not provided
      final itemToAdd = item.id.isEmpty
          ? item.copyWith(id: 'wish_${const Uuid().v4()}')
          : item;

      await _cartRepository.addToWishlist(userId, itemToAdd);
      await loadWishlist();
    } catch (e) {
      errorMessage = e.toString();
    } finally {
      isLoading = false;
    }
  }

  /// Remove item from wishlist by product ID
  @action
  Future<void> removeFromWishlist(String productId) async {
    isLoading = true;
    errorMessage = null;

    try {
      await _cartRepository.removeFromWishlist(userId, productId);
      await loadWishlist();
      selectedProductIds.remove(productId);
    } catch (e) {
      errorMessage = e.toString();
    } finally {
      isLoading = false;
    }
  }

  /// Remove multiple items from wishlist
  @action
  Future<void> removeMultipleFromWishlist(List<String> productIds) async {
    isLoading = true;
    errorMessage = null;

    try {
      await _cartRepository.removeMultipleFromWishlist(userId, productIds);
      await loadWishlist();
      selectedProductIds.clear();
    } catch (e) {
      errorMessage = e.toString();
    } finally {
      isLoading = false;
    }
  }

  /// Remove all selected items
  @action
  Future<void> removeSelectedItems() async {
    if (selectedProductIds.isEmpty) return;
    await removeMultipleFromWishlist(List.from(selectedProductIds));
  }

  /// Clear entire wishlist
  @action
  Future<void> clearWishlist() async {
    isLoading = true;
    errorMessage = null;

    try {
      await _cartRepository.clearWishlist(userId);
      await loadWishlist();
      selectedProductIds.clear();
    } catch (e) {
      errorMessage = e.toString();
    } finally {
      isLoading = false;
    }
  }

  /// Check if product is in wishlist
  @action
  Future<bool> isInWishlist(String productId) async {
    try {
      return await _cartRepository.isInWishlist(userId, productId);
    } catch (e) {
      return false;
    }
  }

  /// Move all wishlist items to cart
  @action
  Future<void> moveAllToCart() async {
    isLoading = true;
    errorMessage = null;

    try {
      await _cartRepository.moveWishlistToCart(userId);
      await loadWishlist();
      selectedProductIds.clear();
    } catch (e) {
      errorMessage = e.toString();
    } finally {
      isLoading = false;
    }
  }

  /// Move specific item to cart
  @action
  Future<void> moveItemToCart(String productId) async {
    isLoading = true;
    errorMessage = null;

    try {
      await _cartRepository.moveWishlistItemToCart(userId, productId);
      await loadWishlist();
      selectedProductIds.remove(productId);
    } catch (e) {
      errorMessage = e.toString();
    } finally {
      isLoading = false;
    }
  }

  /// Move multiple items to cart
  @action
  Future<void> moveMultipleToCart(List<String> productIds) async {
    isLoading = true;
    errorMessage = null;

    try {
      for (final productId in productIds) {
        await _cartRepository.moveWishlistItemToCart(userId, productId);
      }
      await loadWishlist();
      selectedProductIds.clear();
    } catch (e) {
      errorMessage = e.toString();
    } finally {
      isLoading = false;
    }
  }

  /// Move all selected items to cart
  @action
  Future<void> moveSelectedToCart() async {
    if (selectedProductIds.isEmpty) return;
    await moveMultipleToCart(List.from(selectedProductIds));
  }

  /// Toggle item selection
  @action
  void toggleItemSelection(String productId) {
    if (selectedProductIds.contains(productId)) {
      selectedProductIds.remove(productId);
    } else {
      selectedProductIds.add(productId);
    }
  }

  /// Select all items
  @action
  void selectAllItems() {
    selectedProductIds = items.map((item) => item.productId).toList();
  }

  /// Clear selection
  @action
  void clearSelection() {
    selectedProductIds.clear();
  }

  /// Update search query
  @action
  void updateSearchQuery(String query) {
    searchQuery = query;
  }

  /// Update sort order
  @action
  void updateSortBy(String sortOption) {
    sortBy = sortOption;
  }

  /// Get item by product ID
  WishlistItem? getItemByProductId(String productId) {
    try {
      return items.firstWhere((item) => item.productId == productId);
    } catch (e) {
      return null;
    }
  }

  /// Share wishlist (returns formatted string for sharing)
  String getShareableWishlistText() {
    if (items.isEmpty) {
      return 'Check out my wishlist!';
    }

    final buffer = StringBuffer();
    buffer.writeln('My Wishlist:');

    for (final item in items.take(5)) {
      buffer.writeln(
          '- ${item.productName}: \$${item.effectivePrice.toStringAsFixed(2)}');
    }

    if (items.length > 5) {
      buffer.writeln('... and ${items.length - 5} more items');
    }

    return buffer.toString();
  }

  /// Get wishlist recommendations/deals
  /// Returns items that are on sale or have high ratings
  List<WishlistItem> getRecommendedItems() {
    final recommended = <WishlistItem>[];

    // Add items on sale
    recommended.addAll(itemsOnSale);

    // Add highly rated items
    recommended.addAll(
      items.where((item) => item.rating != null && item.rating! >= 4.5),
    );

    // Remove duplicates
    final uniqueIds = <String>{};
    return recommended.where((item) => uniqueIds.add(item.productId)).toList();
  }

  /// Clear error message
  @action
  void clearError() {
    errorMessage = null;
  }

  /// Initialize store
  @action
  Future<void> initialize() async {
    await loadWishlist();
  }

  /// Dispose store
  @action
  void dispose() {
    clearSelection();
    clearError();
    items = [];
  }
}
