import 'package:mobx/mobx.dart';
import 'package:mobile_ai_erp/data/repository/cart/cart_repository.dart';
import 'package:mobile_ai_erp/domain/entity/cart/wishlist_item.dart';
import 'package:uuid/uuid.dart';

part 'wishlist_store.g.dart';

/// MobX store for managing wishlist state and operations
class WishlistStore = WishlistStoreBase with _$WishlistStore;

/// Base class for WishlistStore (generated by build_runner)
abstract class WishlistStoreBase with Store {
  final CartRepository _cartRepository;
  final Uuid _uuid = const Uuid();

  /// Current user ID
  final String userId;

  WishlistStoreBase({
    required CartRepository cartRepository,
    required this.userId,
  }) : _cartRepository = cartRepository;

  // ============ OBSERVABLES ============

  /// List of wishlist items
  @observable
  ObservableList<WishlistItem> items = ObservableList<WishlistItem>();

  /// Loading state
  @observable
  bool isLoading = false;

  /// Error message
  @observable
  String? errorMessage;

  /// Sort order: 'recent', 'price-low', 'price-high', 'name'
  @observable
  String sortBy = 'recent';

  /// Filter/search query
  @observable
  String searchQuery = '';

  /// Selected wishlist item IDs for bulk operations
  @observable
  ObservableList<String> selectedItemIds = ObservableList<String>();

  // ============ COMPUTED ============

  /// Total number of items in wishlist
  @computed
  int get itemCount => items.length;

  /// Total value of wishlist
  @computed
  double get totalWishlistValue =>
      items.fold(0.0, (sum, item) => sum + item.effectivePrice);

  /// Potential savings from wishlist items
  @computed
  double get potentialSavings =>
      items.fold(0.0, (sum, item) => sum + (item.savingsAmount ?? 0.0));

  /// Items on sale in wishlist
  @computed
  List<WishlistItem> get itemsOnSale =>
      items.where((item) => item.hasDiscount).toList();

  /// Items with low stock
  @computed
  List<WishlistItem> get lowStockItems =>
      items.where((item) => item.isLowStock).toList();

  /// Items out of stock
  @computed
  List<WishlistItem> get outOfStockItems =>
      items.where((item) => item.isOutOfStock).toList();

  /// Filtered and sorted wishlist items
  @computed
  List<WishlistItem> get filteredAndSortedItems {
    var filtered = items.toList();

    final query = searchQuery.trim().toLowerCase();
    if (query.isNotEmpty) {
      filtered = filtered.where((item) {
        final productName = item.productName.toLowerCase();
        final category = item.category?.toLowerCase() ?? '';
        final notes = item.notes?.toLowerCase() ?? '';

        // These fields assume your updated WishlistItem keeps variant info.
        final variantId = item.variantId.toLowerCase();
        final sku = item.sku.toLowerCase();
        final size = (item.selectedSize ?? '').toLowerCase();
        final color = (item.selectedColorName ?? '').toLowerCase();

        return productName.contains(query) ||
            category.contains(query) ||
            notes.contains(query) ||
            variantId.contains(query) ||
            sku.contains(query) ||
            size.contains(query) ||
            color.contains(query);
      }).toList();
    }

    final sorted = List<WishlistItem>.from(filtered);

    switch (sortBy) {
      case 'price-low':
        sorted.sort((a, b) => a.effectivePrice.compareTo(b.effectivePrice));
        break;
      case 'price-high':
        sorted.sort((a, b) => b.effectivePrice.compareTo(a.effectivePrice));
        break;
      case 'name':
        sorted.sort((a, b) => a.productName.compareTo(b.productName));
        break;
      case 'recent':
      default:
        sorted.sort((a, b) => b.dateAdded.compareTo(a.dateAdded));
        break;
    }

    return sorted;
  }

  /// Number of selected items
  @computed
  int get selectedItemsCount => selectedItemIds.length;

  /// Selected wishlist items
  @computed
  List<WishlistItem> get selectedItems =>
      items.where((item) => selectedItemIds.contains(item.id)).toList();

  /// Check if wishlist is empty
  @computed
  bool get isEmpty => items.isEmpty;

  // ============ HELPERS ============

  /// Find wishlist item by item ID
  WishlistItem? getItemById(String itemId) {
    try {
      return items.firstWhere((item) => item.id == itemId);
    } catch (_) {
      return null;
    }
  }

  /// Find wishlist item by variant ID
  WishlistItem? getItemByVariantId(String variantId) {
    try {
      return items.firstWhere((item) => item.variantId == variantId);
    } catch (_) {
      return null;
    }
  }

  /// Find wishlist item by product ID
  WishlistItem? getItemByProductId(String productId) {
    try {
      return items.firstWhere((item) => item.productId == productId);
    } catch (_) {
      return null;
    }
  }

  /// Check if a variant already exists in wishlist
  bool containsVariant(String variantId) {
    return items.any((item) => item.variantId == variantId);
  }

  /// Check if an item ID is selected
  bool isItemSelected(String itemId) {
    return selectedItemIds.contains(itemId);
  }

  void _pruneInvalidSelections() {
    final validIds = items.map((item) => item.id).toSet();
    selectedItemIds.removeWhere((id) => !validIds.contains(id));
  }

  // ============ ACTIONS ============

  /// Load wishlist from repository
  @action
  Future<void> loadWishlist() async {
    isLoading = true;
    errorMessage = null;

    try {
      final result = await _cartRepository.getWishlist(userId);
      items = ObservableList<WishlistItem>.of(result);
      _pruneInvalidSelections();
    } catch (e) {
      errorMessage = e.toString();
    } finally {
      isLoading = false;
    }
  }

  /// Add item to wishlist
  /// Prevent duplicate variants from being added.
  @action
  Future<void> addToWishlist(WishlistItem item) async {
    isLoading = true;
    errorMessage = null;

    try {
      if (containsVariant(item.variantId)) {
        return;
      }

      final itemToAdd = item.id.isEmpty
          ? item.copyWith(id: 'wish_${_uuid.v4()}')
          : item;

      await _cartRepository.addToWishlist(userId, itemToAdd);
      await loadWishlist();
    } catch (e) {
      errorMessage = e.toString();
    } finally {
      isLoading = false;
    }
  }

  /// Remove item from wishlist by passing the full item.
  /// Repository currently removes by productId, so we map internally.
  @action
  Future<void> removeFromWishlist(WishlistItem item) async {
    isLoading = true;
    errorMessage = null;

    try {
      await _cartRepository.removeFromWishlist(userId, item.variantId);
      await loadWishlist();
      selectedItemIds.remove(item.id);
    } catch (e) {
      errorMessage = e.toString();
    } finally {
      isLoading = false;
    }
  }

  /// Remove item from wishlist by item ID.
  @action
  Future<void> removeByItemId(String itemId) async {
    final item = getItemById(itemId);
    if (item == null) return;
    await removeFromWishlist(item);
  }

  /// Remove multiple items from wishlist
  @action
  Future<void> removeMultipleFromWishlist(
    List<WishlistItem> itemsToRemove,
  ) async {
    if (itemsToRemove.isEmpty) return;

    isLoading = true;
    errorMessage = null;

    try {
      for (final item in itemsToRemove) {
        await _cartRepository.removeFromWishlist(userId, item.variantId);
      }
      await loadWishlist();
      selectedItemIds.clear();
    } catch (e) {
      errorMessage = e.toString();
    } finally {
      isLoading = false;
    }
  }

  /// Remove all selected items
  @action
  Future<void> removeSelectedItems() async {
    if (selectedItemIds.isEmpty) return;
    await removeMultipleFromWishlist(List<WishlistItem>.from(selectedItems));
  }

  /// Clear entire wishlist
  @action
  Future<void> clearWishlist() async {
    isLoading = true;
    errorMessage = null;

    try {
      await _cartRepository.clearWishlist(userId);
      await loadWishlist();
      selectedItemIds.clear();
    } catch (e) {
      errorMessage = e.toString();
    } finally {
      isLoading = false;
    }
  }

  /// Check if product is in wishlist by productId using repository
  @action
  Future<bool> isInWishlist(String productId) async {
    try {
      return await _cartRepository.isInWishlist(userId, productId);
    } catch (_) {
      return false;
    }
  }

  /// Local check by variantId for immediate UI logic
  bool isVariantInWishlist(String variantId) {
    return containsVariant(variantId);
  }

  /// Move all wishlist items to cart
  @action
  Future<void> moveAllToCart() async {
    isLoading = true;
    errorMessage = null;

    try {
      await _cartRepository.moveWishlistToCart(userId);
      await loadWishlist();
      selectedItemIds.clear();
    } catch (e) {
      errorMessage = e.toString();
    } finally {
      isLoading = false;
    }
  }

  /// Move specific item to cart
  /// Repository currently moves by productId.
  @action
  Future<void> moveItemToCart(WishlistItem item) async {
    isLoading = true;
    errorMessage = null;

    try {
      await _cartRepository.moveWishlistItemToCart(userId, item.variantId);
      await loadWishlist();
      selectedItemIds.remove(item.id);
    } catch (e) {
      errorMessage = e.toString();
    } finally {
      isLoading = false;
    }
  }

  /// Move item to cart by item ID
  @action
  Future<void> moveItemToCartById(String itemId) async {
    final item = getItemById(itemId);
    if (item == null) return;
    await moveItemToCart(item);
  }

  /// Move multiple items to cart
  @action
  Future<void> moveMultipleToCart(List<WishlistItem> itemsToMove) async {
    if (itemsToMove.isEmpty) return;

    isLoading = true;
    errorMessage = null;

    try {
      for (final item in itemsToMove) {
        await _cartRepository.moveWishlistItemToCart(userId, item.variantId);
      }
      await loadWishlist();
      selectedItemIds.clear();
    } catch (e) {
      errorMessage = e.toString();
    } finally {
      isLoading = false;
    }
  }

  /// Move all selected items to cart
  @action
  Future<void> moveSelectedToCart() async {
    if (selectedItemIds.isEmpty) return;
    await moveMultipleToCart(List<WishlistItem>.from(selectedItems));
  }

  /// Toggle item selection
  @action
  void toggleItemSelection(String itemId) {
    if (selectedItemIds.contains(itemId)) {
      selectedItemIds.remove(itemId);
    } else {
      selectedItemIds.add(itemId);
    }
  }

  /// Select all items
  @action
  void selectAllItems() {
    selectedItemIds = ObservableList<String>.of(items.map((item) => item.id));
  }

  /// Clear selection
  @action
  void clearSelection() {
    selectedItemIds.clear();
  }

  /// Update search query
  @action
  void updateSearchQuery(String query) {
    searchQuery = query;
  }

  /// Update sort order
  @action
  void updateSortBy(String sortOption) {
    sortBy = sortOption;
  }

  /// Share wishlist (returns formatted string for sharing)
  String getShareableWishlistText() {
    if (items.isEmpty) {
      return 'Check out my wishlist!';
    }

    final buffer = StringBuffer();
    buffer.writeln('My Wishlist:');

    for (final item in items.take(5)) {
      final variantText = [
        if ((item.selectedColorName ?? '').isNotEmpty) item.selectedColorName,
        if ((item.selectedSize ?? '').isNotEmpty) item.selectedSize,
      ].whereType<String>().join(' / ');

      final displayName = variantText.isEmpty
          ? item.productName
          : '${item.productName} ($variantText)';

      buffer.writeln(
        '- $displayName: \$${item.effectivePrice.toStringAsFixed(2)}',
      );
    }

    if (items.length > 5) {
      buffer.writeln('... and ${items.length - 5} more items');
    }

    return buffer.toString();
  }

  /// Get wishlist recommendations/deals
  /// Returns items that are on sale or have high ratings
  List<WishlistItem> getRecommendedItems() {
    final recommended = <WishlistItem>[];

    recommended.addAll(itemsOnSale);
    recommended.addAll(
      items.where((item) => item.rating != null && item.rating! >= 4.5),
    );

    final uniqueVariantIds = <String>{};
    return recommended
        .where((item) => uniqueVariantIds.add(item.variantId))
        .toList();
  }

  /// Clear error message
  @action
  void clearError() {
    errorMessage = null;
  }

  /// Initialize store
  @action
  Future<void> initialize() async {
    await loadWishlist();
  }

  /// Dispose store
  @action
  void dispose() {
    clearSelection();
    clearError();
    items.clear();
  }
}
